backends/bluezdbus/manager: Cancel the discovery on disconnect to avoid a timeout
hbldh/bleak pull request #1092
Opened 2022-10-25 15:09 UTC by arthur-proglove

If a device disconnects while waiting for the services to be discovered, the manager will wait forever.
This commit fixes that by introducing a context to the _wait_condition method with an exception on disconnect.

Pull Request Guidelines for Bleak
---------------------------------

Before you submit a pull request, check that it meets these guidelines:

1. If the pull request adds functionality, the docs should be updated.
2. Modify the `CHANGELOG.rst`, describing your changes as is specified by the
   guidelines in that document.
3. The pull request should work for Python 3.7+ on the following platforms:
    - Windows 10, version 16299 (Fall Creators Update) and greater
    - Linux distributions with BlueZ >= 5.43
    - OS X / macOS >= 10.11
4. Squash all your commits on your PR branch, if the commits are not solving
   different problems and you are committing them in the same PR. In that case,
   consider making several PRs instead.
5. Feel free to add your name as a contributor to the `AUTHORS.rst` file!

2022-10-25 16:38 UTC, dlech commented
I agree this should be fixed, but I would like to suggest a different way of doing it. Instead of introducing a new class, we should be able to use `asyncio.wait(..., return_when=FIRST_COMPLETED)` to wait for either ServicesResolved==True or "Connected"==False. If the latter wins the race, raise an exception.

2022-10-26 07:28 UTC, arthur-proglove commented
> I agree this should be fixed, but I would like to suggest a different way of doing it. Instead of introducing a new class, we should be able to use `asyncio.wait(..., return_when=FIRST_COMPLETED)` to wait for either ServicesResolved==True or "Connected"==False. If the latter wins the race, raise an exception.

Oh, thank you for highlighting this function, I only knew `gather`. 

I tried to make something prettier then accessing directly `self._properties[device_path][defs.DEVICE_INTERFACE]["Connected"]` in the callback but could not find something more elegant. Using the device watcher callbacks seemed overkill.

2022-10-26 15:11 UTC, dlech requested changes
Good start. However, `_wait_condition` is a generic function, so we should leave it that way. 

The `asyncio.wait()` logic looks right, but it should replace `await self._wait_condition(device_path, "ServicesResolved", True)` in `get_services()`. And the two tasks can be defined at `self._wait_condition(device_path, "ServicesResolved", True)` and `self._wait_condition(device_path, "Connected", False)`.

2022-10-27 15:55 UTC, dlech approved these changes
Looks great, thanks!

2022-10-27 15:56 UTC, merged